### ISSUE TITLE
Make diff tool path configurable

### ISSUE THREAD

**Issue by bertspaan** [histograph/node-diff-utility#1]
`hashed-diff` is not installed by default, it would be a good idea to add a configuration option to histograph/config and make the diff command line argument that IO or node-diff-utility uses configurable!

See https://github.com/histograph/io/commit/51f2d51e8c45af58281395d480607638b9f0a70a.

**Comment by lodewijkloos** [comment]
I'll make the diff-tool configurable in the api/io section of the config (config/histograph.default.yml). I'll add the diff-tool name as an argument to the call function in node-diff-utility/index.js .

**Comment by bertspaan** [comment]
:+1:

**Comment by jobspierings** [comment]
done and deployed by 11/1/2016
